### ISSUE TITLE
Wildcard support?

### ISSUE THREAD

**Issue by OmgImAlexis** [dzek69/brotli-cli#5]
I'd be nice to use `brotli-cli compress ./dist/**/*` and have it compress all files skipping the existing compressed ones.

**Comment by OmgImAlexis** [comment]
Looks like it can be done via the glob argument.

```
brotli-cli compress --glob './client/dist/*.html' --glob './client/dist/assets/*.css' --glob './client/dist/assets/*.js'
```

**Comment by dzek69** [comment]
I forgot to update README with recent updates adding glob support, sorry 😞 I will do that hopefully later today
